### ISSUE TITLE
Update FunC to 0.4.4

### ISSUE THREAD

**Issue by novusnota** [novusnota/prism-ton#1]
See:
* History https://docs.ton.org/develop/func/changelog
* Sources https://github.com/ton-blockchain/ton/tree/master/crypto/func
* 0.5.0 update https://github.com/ton-blockchain/ton/pull/1026
* Highlight.js PR https://github.com/orbs-network/highlightjs-func/pull/1

**Comment by mm8191** [comment]
سلام لطفا پول ک اشتباه اومده حساب ولت برگردونید ب ولت ام باتشکر شماره ولتم هس داخل تراکنش هات برنگردونید اتوماتیک سیستم برمیگردونه
